baseURL = 'https://blog.qinyan.org/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = false
title = '言杂录'
theme = 'PaperMod'

enableRobotsTXT = true
hasCJKLanguage = true
enableEmoji = true
googleAnalytics = "G-54JQ3PJWRJ"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    defaultTheme = 'auto'
    author = { name = "qinyan" }
    showReadingTime = true
    showShareButtons = false
    showPostMeta = true
    ShowCodeCopyButtons = true
    ShowToc = true
    ShowBreadCrumbs = true
    ShowPostNavLinks = true
    description = "偶尔会更新的博客"
    comments = true

    [params.homeInfoParams]
        Title = "👋 欢迎来到言杂录"
        Content = ""

    [[params.socialIcons]]
        name = "rss"
        url = "/index.xml"

    [[params.socialIcons]]
        name = "uptimerobot"
        url = "https://stats.uptimerobot.com/3u1qV7Swq6/800035701"

    [params.assets]
        disableHLJS = true
        favicon = "/favicon.ico"
        favicon16x16 = "/favicon-96x96.png"
        favicon32x32 = "/favicon-96x96.png"
        apple_touch_icon = "/apple-touch-icon.png"
        
    [params.fuseOpts]
        isCaseSensitive = false
        shouldSort = true
        location = 0
        distance = 1000
        threshold = 0.4
        minMatchCharLength = 0
        keys = ["title", "permalink", "summary", "content"]

[permalinks]
    posts = "/archives/:slug/"

[languages]
    [languages.zh]
        title = "言杂录"
        languageCode = "zh-CN"
        languageName = "Chinese"
        contentDir = "content/zh"
        weight = 1

    [languages.en]
        title = "Miscellanyan"
        languageCode = "en-US"
        languageName = "English"
        contentDir = "content/en"
        weight = 2
        
        [languages.en.params]
            description = "An occasionally updated blog"
            
            [languages.en.params.homeInfoParams]
                Title = "👋 Welcome to Miscellanyan"
                Content = ""
            
            [[languages.en.params.socialIcons]]
                name = "rss"
                url = "/en/index.xml"
            
            [[languages.en.params.socialIcons]]
                name = "uptimerobot"
                url = "https://stats.uptimerobot.com/3u1qV7Swq6/800035701"
        
[[languages.zh.menu.main]]
    identifier = "archives"
    name = "📚 归档"
    url = "/archives/"
    weight = 5

[[languages.zh.menu.main]]
    identifier = "tags"
    name = "🏷️ 标签"
    url = "/tags/"
    weight = 10

[[languages.zh.menu.main]]
    identifier = "categories"
    name = "📁 分类"
    url = "/categories/"
    weight = 15

[[languages.zh.menu.main]]
    identifier = "search"
    name = "🔍 搜索"
    url = "/search/"
    weight = 20

[[languages.zh.menu.main]]
    identifier = "guestbook"
    name = "💬 留言"
    url = "/guestbook/"
    weight = 25

[[languages.en.menu.main]]
    identifier = "archives"
    name = "📚 Archives"
    url = "/archives/"
    weight = 5

[[languages.en.menu.main]]
    identifier = "tags"
    name = "🏷️ Tags"
    url = "/tags/"
    weight = 10

[[languages.en.menu.main]]
    identifier = "categories"
    name = "📁 Categories"
    url = "/categories/"
    weight = 15

[[languages.en.menu.main]]
    identifier = "search"
    name = "🔍 Search"
    url = "/search/"
    weight = 20

[[languages.en.menu.main]]
    identifier = "guestbook"
    name = "💬 Guestbook"
    url = "/guestbook/"
    weight = 25

[markup]
  [markup.highlight]
    noClasses = false
    style = "native"
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
