[build]
publish = "public"
command = "hugo --gc --minify --baseURL $URL"

[build.environment]
    HUGO_VERSION = "0.153.0"
    HUGO_EXTENDED = "true"

[context.production.environment]
HUGO_ENV = "production"
